services:

  swpm-postgres:
    image: postgres:16-alpine
    container_name: swpm-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  swpm-mqtt:
    image: eclipse-mosquitto:2.0
    container_name: swpm-mqtt
    restart: unless-stopped

    ports:
      - "${MQTT_PORT:-1883}:1883"

    volumes:
      - ./infra/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
