export const PERMISSIONS = [
  'dashboard.view',
  'site.view',
  'site.manage',
  'device.view',
  'device.manage',
  'asset.view',
  'telemetry.view',
  'alarm.view',
  'alarm.ack',
  'alarm.manage',
  'report.view',
  'report.export',
  'user.view',
  'user.manage',
  'audit.view',
  'pump.control',
  'command.view',
  'command.manage',
  'sensor.manage',
  'area.manage',
  'system.manage',
] as const;

export type Permission = typeof PERMISSIONS[number];

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ENGINEER: 'ENGINEER',
  OPERATOR: 'OPERATOR',
  VIEWER: 'VIEWER',
} as const;

export type RoleName = keyof typeof ROLES;

// PRD Section 50: Role Permission Matrix
export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  SUPER_ADMIN: [
    'dashboard.view',
    'site.view',
    'site.manage',
    'device.view',
    'device.manage',
    'asset.view',
    'telemetry.view',
    'alarm.view',
    'alarm.ack',
    'alarm.manage',
    'report.view',
    'report.export',
    'user.view',
    'user.manage',
    'audit.view',
    'pump.control',
    'command.view',
    'command.manage',
    'sensor.manage',
    'area.manage',
    'system.manage',
  ],
  ENGINEER: [
    'dashboard.view',
    'site.view',
    'site.manage',
    'device.view',
    'device.manage',
    'asset.view',
    'telemetry.view',
    'alarm.view',
    'alarm.ack',
    'alarm.manage',
    'report.view',
    'report.export',
    'pump.control',
    'command.view',
    'command.manage',
    'sensor.manage',
    'area.manage',
    'audit.view',
  ],
  OPERATOR: [
    'dashboard.view',
    'site.view',
    'device.view',
    'asset.view',
    'telemetry.view',
    'alarm.view',
    'alarm.ack',
    'pump.control',
    'command.view',
    'report.view',
    'report.export',
  ],
  VIEWER: [
    'dashboard.view',
    'site.view',
    'device.view',
    'asset.view',
    'telemetry.view',
    'alarm.view',
    'command.view',
    'report.view',
  ],
};

export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIAL: 'AUTH_INVALID_CREDENTIAL',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_OFFLINE: 'DEVICE_OFFLINE',
  TELEMETRY_INVALID: 'TELEMETRY_INVALID',
  ALARM_NOT_ACTIVE: 'ALARM_NOT_ACTIVE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
